language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
notifications:
    email:
        on_failure: change
        on_success: change
    slack: astrochats:tV2KNwL9jXSGSv5KhulGNVro
git:
    depth: 3

before_install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --system --set auto_update_conda false
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
install:
    # - conda config --add channels conda-forge
    # - conda install --yes python=$TRAVIS_PYTHON_VERSION scipy matplotlib astropy beautifulsoup4 bokeh gitpython palettable psutil seaborn tqdm coveralls
    # - xargs -L 1 pip install < requirements.txt
    # - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
    # - git config --global user.email "you@example.com"
    # - git config --global user.name "Your Name"
    - git clone https://github.com/astrocatalogs/testcat.git
    # - cd $TRAVIS_REPO_SLUG
    # - pip install -r requirements.txt
    - cat requirements.txt | cut -f1 -d"#" | sed '/^\s*$/d' | xargs -n 1 pip install

# Run test
script:
    - coverage run -a -m astrocats ./testcat --travis import --archived
    # - coverage run -a -m astrocats setup
    # - echo "travis_fold:start:IMPORT Importing data"
    # # Run twice to test deleting old entries
    # - coverage run -a -m astrocats catalog import -v --min-task-priority test
    # - coverage run -a -m astrocats catalog import -a --task-groups meta
    # - coverage run -a -m astrocats catalog analyze -v --count
    # - echo "travis_fold:end:IMPORT Importing data done"
    # - echo "travis_fold:start:GIT checking git repos"
    # - coverage run -a -m astrocats catalog git-status
    # - coverage run -a -m astrocats catalog git-reset-local
    # - coverage run -a -m astrocats catalog git-status
    # - coverage run -a -m astrocats catalog git-reset-origin
    # - git config --global user.email "you@example.com"
    # - git config --global user.name "Your Name"
    # - coverage run -a -m astrocats catalog git-push --travis
    # - echo "travis_fold:end:GIT completed git checks"
#    - echo "travis_fold:start:MAKE Making catalog"
#    - cd astrocats/supernovae/scripts
#    - python make-catalog.py -tr
#    - echo "travis_fold:end:MAKE Making catalog done"

# Run coveralls
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then coveralls; fi
